---
:orientdb:
  :production:
   :server: 172.28.50.25  # localhost
   :user:  hctw
   :password: a***k 
   :database: o
  :test:
   :server: 10.222.148.109
   :user: hctw
   :password: s*p**
   :database: test
  :development:
   :server: 10.222.148.109
   :user: hctw
   :password: s*p**
   :database: demo
:port: 2480
:logger: stdout           # 'file' or 'stdout'

# hfx: 101
