---
:orientdb:
 :server: localhost # 172.28.50.109 # localhost   #mailout.halfgarten-capital.de
 :port: 2480
 :logger: stdout           # 'file' or 'stdout'
 :database: 
   :production: time_production
   :development: time_dev
   :test: tempera
 :admin:
   :user: hctw
   :pass: hc
 :auth:
   :user: topo
   :pass: focus

# hfx: 101
